#!/bin/bash
#select fresh folder first to store sources, then download
#it will bring evoparsons-server, psi, psifx and puzzles to folder 

mkdir tmp 
cd tmp 
git init 
git remote add -f origin https://github.com/cereal-lab/EvoParsons.git
git config core.sparseCheckout true
echo evoparsons >> .git/info/sparse-checkout
echo lib >> .git/info/sparse-checkout
git checkout ${BRANCH}
git pull origin ${BRANCH}
cd ..
mv tmp/evoparsons evoparsons 
mv tmp/lib lib
#svn checkout "${SVNTARGET}ParsonsLibraries/Programs/${PROGRAMS}" Programs >/dev/null
#svn checkout "${SVNTARGET}ParsonsLibraries/Programs/${TRANS}" Transforms >/dev/null
mkdir scripts
mkdir docker
wget "https://raw.githubusercontent.com/cereal-lab/EvoParsons/${BRANCH}/scripts/build-server" --content-disposition --no-check-certificate -O ./scripts/build-server >/dev/null
wget "https://raw.githubusercontent.com/cereal-lab/EvoParsons/${BRANCH}/scripts/evoparsons-server" --content-disposition --no-check-certificate -O ./scripts/evoparsons-server >/dev/null
wget "https://raw.githubusercontent.com/cereal-lab/EvoParsons/${BRANCH}/docker/supervisord.conf" --content-disposition --no-check-certificate -O ./docker/supervisord.conf >/dev/null
#svn checkout "${SVNTARGET}docker" docker >/dev/null