#!/bin/bash
#select fresh folder first to store sources, then download
#it will bring evoparsons-server, psi, psifx and puzzles to folder 

SVNTARGET="https://github.com/cereal-lab/EvoParsons/branches/${BRANCH}/"

svn checkout "${SVNTARGET}evoparsons/broker" evoparsons/broker >/dev/null
svn checkout "${SVNTARGET}evoparsons/ecj" evoparsons/ecj >/dev/null
svn checkout "${SVNTARGET}evoparsons/github" evoparsons/github >/dev/null
svn checkout "${SVNTARGET}evoparsons/repo" evoparsons/repo >/dev/null
svn checkout "${SVNTARGET}evoparsons/rmishared" evoparsons/rmishared >/dev/null
svn checkout "${SVNTARGET}evoparsons/utils" evoparsons/utils >/dev/null
svn checkout "${SVNTARGET}lib" lib >/dev/null
#svn checkout "${SVNTARGET}ParsonsLibraries/Programs/${PROGRAMS}" Programs >/dev/null
#svn checkout "${SVNTARGET}ParsonsLibraries/Programs/${TRANS}" Transforms >/dev/null
mkdir scripts
mkdir docker
wget "https://raw.githubusercontent.com/cereal-lab/EvoParsons/${BRANCH}/scripts/build-server" --content-disposition --no-check-certificate -O ./scripts/build-server >/dev/null
wget "https://raw.githubusercontent.com/cereal-lab/EvoParsons/${BRANCH}/scripts/evoparsons-server" --content-disposition --no-check-certificate -O ./scripts/evoparsons-server >/dev/null
wget "https://raw.githubusercontent.com/cereal-lab/EvoParsons/${BRANCH}/docker/supervisord.conf" --content-disposition --no-check-certificate -O ./docker/supervisord.conf >/dev/null
#svn checkout "${SVNTARGET}docker" docker >/dev/null

