#!/bin/sh
#this script launches evoparsons server (execute it inside bin folder after build) 
java -cp "ecj.24.jar:jetty-all-9.4.49.v20220914-uber.jar:jetty-util-ajax-9.4.11.v20180605.jar:mongo-java-driver-3.10.2.jar:evoparsons.jar" -Dfile=${BROKER_CONFIG} evoparsons.broker.Startup