#!/bin/bash
#this script launches evoparsons server (execute it inside bin folder after build) 
#example of parameters bellow
java -cp "ecj.24.jar:jetty-9.4.10.v20180503.jar:jetty-util-ajax-9.4.11.v20180605.jar:evoparsons.jar" -Dfile=${BROKER_CONFIG} evoparsons.broker.Startup